name: PR lint
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - '**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: install
        run: time npm ci 
      - name: lint fix
        run: time npm run lint -- --fix

      - name: Display error log
        if: ${{ failure() }}
        run: cat /github/home/.npm/_logs/*.log

  test:
    needs: [lint]
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: install
        run: time npm ci 
      - name: install playwright
        run: time npx playwright install --with-deps
      - name: build storybook
        run: time npm run build-storybook --quiet
      - name: test-storybook
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server docs --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test-storybook"
      - name: Display error log
        if: ${{ failure() }}
        run: cat /github/home/.npm/_logs/*.log