name: test-run
on: push
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - run: echo "test 1 success"
      - name: use node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: '20.x'
      - name: install
        run: npm ci 
      - name: lint fix
        run: npm run lint -- --fix